services:
  api:
    build:
      context: ./api/EatAndWatch
      network: host
    ports:
      - "127.0.0.1:5144:5144"
    environment:
      - ASPNETCORE_URLS=http://+:5144
    volumes:
      - ./api/EatAndWatch/EatAndWatch/data:/app/data


  web:
    build:
      context: ./weboldal
      network: host
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - api
